# Module manifest for module 'Shape'
#
# Generated by: James Brundage
#
# Generated on: 1/1/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Shape.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'e846578b-a9f3-408f-9f5c-828210c71939'

# Author of this module
Author = 'James Brundage'

# Company or vendor of this module
CompanyName = 'Start Automating'

# Copyright statement for this module
Copyright = '2025 Start Automating'

# Description of the functionality provided by this module
Description = 'CSS Shape Generator'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = 'Shape.types.ps1xml'

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-Shape'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
# CmdletsToExport = '*'

# Variables to export from this module
#VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Shape', 'circle','ellipse',
    'circle','ellipse',
    'inset','rect',
    'polygon',
    # Not aliasing to `path` due to potential confusion.
    'path2d',
    'xywh', 
    'css.circle', 'css.ellipse', 
    'css.inset', 'css.rect', 
    'css.polygon', 'css.path','css.path2d', 'css.xywh',
    'css.shape'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/PowerShellWeb/Shape/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/PowerShellWeb/Shape'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## Shape 0.1:

Shape makes CSS Shapes (#1)

* It has a basic build (checkout, ezout, run local action) (#2)
* It has a GitHub action (#3)
* It consists of a single command, `Get-Shape` (#4)
  * `Get-Shape` has aliases for each [basic shape](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/basic-shape) type (#16) 
  * `Get-Shape` returns all of its input in a pseudo type, `Shape`
* `Shape` defines a shape based off of `.Input`
  * `Shape.CSS` gets the shape as CSS (#5)
  * `Shape.ToString()` will return the .CSS (#6)
  * `Shape.Help` contains helpful links (#7)
  * `Shape.ShapeTypePattern` gets a pattern for known shape types (#8)
  * `Shape.ShapeType` returns shape type based off of the input (#9)
  * `Shape` displays CSS by default (#10)
* The shape module has simple tests (#11)
* `Shape` covers the GitHub Basics
  * It has a README (#17)
  * It supports sponorship (#15)
  * It has a security guide (#14)
  * It has a contributing guide (#13)
  * It has a code of conduct (#12)
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

